package com.yizhaoqi.smartpai.service;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.yizhaoqi.smartpai.client.DeepSeekClient;
import com.yizhaoqi.smartpai.entity.SearchResult;
import com.yizhaoqi.smartpai.service.ConversationService;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.dao.DataAccessException;
import org.springframework.data.redis.core.RedisOperations;
import org.springframework.data.redis.core.RedisTemplate;
import org.springframework.data.redis.core.SessionCallback;
import org.springframework.stereotype.Service;
import org.springframework.web.socket.TextMessage;
import org.springframework.web.socket.WebSocketSession;

import java.time.Duration;
import java.util.*;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.ConcurrentHashMap;

/**
 * 聊天处理服务
 * 负责处理WebSocket聊天消息和管理对话历史
 * 
 * @author Generated by Assistant
 */
@Service
public class ChatHandler {
    
    private static final Logger logger = LoggerFactory.getLogger(ChatHandler.class);
    private final RedisTemplate<String, String> redisTemplate;
    private final HybridSearchService searchService;
    private final DeepSeekClient deepSeekClient;
    private final ConversationService conversationService;
    private final ObjectMapper objectMapper;
    
    // 用于存储每个会话的完整响应
    private final Map<String, StringBuilder> responseBuilders = new ConcurrentHashMap<>();
    // 用于跟踪每个会话的响应完成状态
    private final Map<String, CompletableFuture<String>> responseFutures = new ConcurrentHashMap<>();
    // 停止标志 - 简单方案
    private final Map<String, Boolean> stopFlags = new ConcurrentHashMap<>();

    public ChatHandler(RedisTemplate<String, String> redisTemplate,
                      HybridSearchService searchService,
                      DeepSeekClient deepSeekClient,
                      ConversationService conversationService) {
        this.redisTemplate = redisTemplate;
        this.searchService = searchService;
        this.deepSeekClient = deepSeekClient;
        this.conversationService = conversationService;
        this.objectMapper = new ObjectMapper();
    }

    public void processMessage(String userId, String userMessage, WebSocketSession session) {
        logger.info("开始处理消息，用户ID: {}, 会话ID: {}", userId, session.getId());
        try {
            // 1. 获取或创建会话 ID
            String conversationId = getOrCreateConversationId(userId);
            logger.info("会话ID: {}, 用户ID: {}", conversationId, userId);
            
            // 为当前会话创建响应构建器
            responseBuilders.put(session.getId(), new StringBuilder());
            // 创建一个CompletableFuture来跟踪响应完成状态
            CompletableFuture<String> responseFuture = new CompletableFuture<>();
            responseFutures.put(session.getId(), responseFuture);
            
            // 2. 获取对话历史
            List<Map<String, String>> history = getConversationHistory(conversationId);
            logger.debug("获取到 {} 条历史对话", history.size());
            
            // 3. 执行带权限过滤的混合搜索
            List<SearchResult> searchResults = searchService.searchWithPermission(userMessage, userId, 5);
            logger.debug("搜索结果数量: {}", searchResults.size());
            
            // 4. 构建上下文
            String context = buildContext(searchResults);
            
            // 5. 调用 DeepSeek API 并处理流式响应
            logger.info("调用DeepSeek API生成回复");
            deepSeekClient.streamResponse(userMessage, context, history,
                chunk -> {
                    // 累积响应内容
                    StringBuilder responseBuilder = responseBuilders.get(session.getId());
                    if (responseBuilder != null) {
                        responseBuilder.append(chunk);
                    }
                    sendResponseChunk(session, chunk);
                },
                () -> {
                    logger.info("DeepSeek流式响应完成回调，将持久化会话");
                    StringBuilder responseBuilder = responseBuilders.get(session.getId());
                    String completeResponse = responseBuilder != null ? responseBuilder.toString() : "";

                    sendCompletionNotification(session);
                    finalizeConversation(conversationId, userId, userMessage, completeResponse);

                    responseBuilders.remove(session.getId());
                    CompletableFuture<String> future = responseFutures.remove(session.getId());
                    if (future != null && !future.isDone()) {
                        future.complete(completeResponse);
                    }
                    logger.info("消息处理完成，用户ID: {}", userId);
                },
                error -> {
                    // 处理错误并完成future
                    handleError(session, error);
                    // 发送响应完成通知（错误情况）
                    sendCompletionNotification(session);
                    responseFuture.completeExceptionally(error);
                    // 清理会话响应构建器
                    responseBuilders.remove(session.getId());
                    responseFutures.remove(session.getId());
                });

            
        } catch (Exception e) {
            logger.error("处理消息错误: {}", e.getMessage(), e);
            handleError(session, e);
            // 清理会话响应构建器
            responseBuilders.remove(session.getId());
            // 清理响应future
            CompletableFuture<String> future = responseFutures.remove(session.getId());
            if (future != null && !future.isDone()) {
                future.completeExceptionally(e);
            }
        }
    }

//    private String getOrCreateConversationId(String userId) {
//        String key = "user:" + userId + ":current_conversation";
//        String conversationId = redisTemplate.opsForValue().get(key);
//
//        if (conversationId == null) {
//            conversationId = UUID.randomUUID().toString();
//            redisTemplate.opsForValue().set(key, conversationId, Duration.ofDays(7));
//            logger.info("为用户 {} 创建新的会话ID: {}", userId, conversationId);
//        } else {
//            logger.info("获取到用户 {} 的现有会话ID: {}", userId, conversationId);
//        }
//
//        return conversationId;
//    }
//
//    private List<Map<String, String>> getConversationHistory(String conversationId) {
//        String key = "conversation:" + conversationId;
//        String json = redisTemplate.opsForValue().get(key);
//        try {
//            if (json == null) {
//                logger.debug("会话 {} 没有历史记录", conversationId);
//                return new ArrayList<>();
//            }
//
//            List<Map<String, String>> history = objectMapper.readValue(json, new TypeReference<List<Map<String, String>>>() {});
//            logger.debug("读取到会话 {} 的 {} 条历史记录", conversationId, history.size());
//            return history;
//        } catch (JsonProcessingException e) {
//            logger.error("解析对话历史出错: {}, 会话ID: {}", e.getMessage(), conversationId, e);
//            return new ArrayList<>();
//        }
//    }
//
//    private void updateConversationHistory(String conversationId, String userMessage, String response) {
//        String key = "conversation:" + conversationId;
//        List<Map<String, String>> history = getConversationHistory(conversationId);
//
//        // 获取当前时间戳
//        String currentTimestamp = java.time.LocalDateTime.now().format(java.time.format.DateTimeFormatter.ofPattern("yyyy-MM-dd'T'HH:mm:ss"));
//
//        // 添加用户消息（带时间戳）
//        Map<String, String> userMsgMap = new HashMap<>();
//        userMsgMap.put("role", "user");
//        userMsgMap.put("content", userMessage);
//        userMsgMap.put("timestamp", currentTimestamp);
//        history.add(userMsgMap);
//
//        // 添加助手回复（带时间戳）
//        Map<String, String> assistantMsgMap = new HashMap<>();
//        assistantMsgMap.put("role", "assistant");
//        assistantMsgMap.put("content", response);
//        assistantMsgMap.put("timestamp", currentTimestamp);
//        history.add(assistantMsgMap);
//
//        // 限制历史记录长度，保留最近的20条消息
//        if (history.size() > 20) {
//            history = history.subList(history.size() - 20, history.size());
//        }
//
//        try {
//            String json = objectMapper.writeValueAsString(history);
//            redisTemplate.opsForValue().set(key, json, Duration.ofDays(7));
//            logger.debug("更新会话历史，会话ID: {}, 总消息数: {}", conversationId, history.size());
//        } catch (JsonProcessingException e) {
//            logger.error("序列化对话历史出错: {}, 会话ID: {}", e.getMessage(), conversationId, e);
//        }
//    }

    // 获取会话id
    private String getOrCreateConversationId(String userId) {
        String key = "user:" + userId + ":current_conversation";
        String conversationId = redisTemplate.opsForValue().get(key);

        if (conversationId == null) {
            conversationId = UUID.randomUUID().toString();
            redisTemplate.opsForValue().set(key, conversationId, Duration.ofDays(7));
            logger.info("为用户 {} 创建新的会话ID: {}", userId, conversationId);
        } else {
            logger.info("获取到用户 {} 的现有会话ID: {}", userId, conversationId);
        }

        return conversationId;
    }

    // 获取对话历史
    private List<Map<String, String>> getConversationHistory(String conversationId) {
        String key = "conversation:" + conversationId + ":messages";
        try {
            // 从List中获取所有消息，按索引范围（0到-1表示所有）
            List<String> messageJsons = redisTemplate.opsForList().range(key, 0, -1);

            if (messageJsons == null || messageJsons.isEmpty()) {
                logger.debug("会话 {} 没有历史记录", conversationId);
                return new ArrayList<>();
            }

            List<Map<String, String>> history = new ArrayList<>();
            for (String messageJson : messageJsons) {
                Map<String, String> message = objectMapper.readValue(messageJson,
                        new TypeReference<Map<String, String>>() {});
                history.add(message);
            }

            logger.debug("读取到会话 {} 的 {} 条历史记录", conversationId, history.size());
            return history;
        } catch (JsonProcessingException e) {
            logger.error("解析对话历史出错: {}, 会话ID: {}", e.getMessage(), conversationId, e);
            return new ArrayList<>();
        }
    }

    // 更新历史记录
    private void updateConversationHistory(String conversationId, String userMessage, String response) {
        String key = "conversation:" + conversationId + ":messages";
        String metadataKey = "conversation:" + conversationId + ":metadata";

        // 获取当前时间戳
        String currentTimestamp = java.time.LocalDateTime.now()
                .format(java.time.format.DateTimeFormatter.ofPattern("yyyy-MM-dd'T'HH:mm:ss"));

        try {
            // 创建用户消息JSON
            Map<String, String> userMsgMap = new LinkedHashMap<>();
            userMsgMap.put("role", "user");
            userMsgMap.put("content", userMessage);
            userMsgMap.put("timestamp", currentTimestamp);
            String userMsgJson = objectMapper.writeValueAsString(userMsgMap);

            // 创建助手回复JSON
            Map<String, String> assistantMsgMap = new LinkedHashMap<>();
            assistantMsgMap.put("role", "assistant");
            assistantMsgMap.put("content", response);
            assistantMsgMap.put("timestamp", currentTimestamp);
            String assistantMsgJson = objectMapper.writeValueAsString(assistantMsgMap);

            // 使用事务保证原子性
            redisTemplate.execute(new SessionCallback<Object>() {
                @Override
                public Object execute(RedisOperations operations) throws DataAccessException {
                    operations.multi();

                    // 向List尾部添加新消息
                    operations.opsForList().rightPushAll(key, userMsgJson, assistantMsgJson);

                    // 检查并限制List长度（保留最近40条消息，即10轮对话）
//                    operations.opsForList().trim(key, -40, -1);

                    // 更新会话元数据（最后活动时间）
                    Map<String, String> metadata = new HashMap<>();
                    metadata.put("lastActivity", currentTimestamp);
                    metadata.put("messageCount", String.valueOf(getMessageCount(conversationId) + 2));
                    try {
                        String metadataJson = objectMapper.writeValueAsString(metadata);
                        operations.opsForValue().set(metadataKey, metadataJson, Duration.ofDays(7));
                    } catch (JsonProcessingException e) {
                        throw new RuntimeException(e);
                    }

                    // 设置过期时间
                    operations.expire(key, Duration.ofDays(7));

                    return operations.exec();
                }
            });

            logger.debug("更新会话历史，会话ID: {}, 新增2条消息", conversationId);

        } catch (JsonProcessingException e) {
            logger.error("序列化对话历史出错: {}, 会话ID: {}", e.getMessage(), conversationId, e);
        }
    }

    private void finalizeConversation(String conversationId, String userId, String userMessage, String response) {
        try {
            updateConversationHistory(conversationId, userMessage, response);
            persistConversation(userId, userMessage, response);
        } catch (Exception e) {
            logger.error("持久化对话失败: {}, 会话ID: {}", e.getMessage(), conversationId, e);
        }
    }

    private void persistConversation(String userId, String userMessage, String response) {
        try {
            conversationService.recordConversation(userId, userMessage, response);
            logger.debug("会话已持久化到数据库，用户ID: {}, 问题长度: {}, 回答长度: {}", userId, userMessage.length(), response.length());
        } catch (Exception e) {
            logger.error("数据库持久化失败，用户ID: {}, 错误: {}", userId, e.getMessage(), e);
        }
    }

    // 辅助方法：获取会话的消息数量
    private long getMessageCount(String conversationId) {
        String key = "conversation:" + conversationId + ":messages";
        Long size = redisTemplate.opsForList().size(key);
        return size != null ? size : 0;
    }

    private String buildContext(List<SearchResult> searchResults) {
        if (searchResults == null || searchResults.isEmpty()) {
            // 返回空字符串，让 DeepSeekClient 按"无检索结果"逻辑处理
            return "";
        }

        final int MAX_SNIPPET_LEN = 300; // 单段最长字符数，超出截断
        StringBuilder context = new StringBuilder();
        for (int i = 0; i < searchResults.size(); i++) {
            SearchResult result = searchResults.get(i);
            String snippet = result.getTextContent();
            if (snippet.length() > MAX_SNIPPET_LEN) {
                snippet = snippet.substring(0, MAX_SNIPPET_LEN) + "…";
            }
            String fileLabel = result.getFileName() != null ? result.getFileName() : "unknown";
            context.append(String.format("[%d] (%s) %s\n", i + 1, fileLabel, snippet));
        }
        return context.toString();
    }

    private void sendResponseChunk(WebSocketSession session, String chunk) {
        try {
            // 检查是否需要停止发送
            if (Boolean.TRUE.equals(stopFlags.get(session.getId()))) {
                logger.debug("检测到停止标志，跳过发送响应块");
                return;
            }
            
            // 将chunk包装成JSON格式，匹配前端期望的数据结构
            Map<String, String> chunkResponse = Map.of("chunk", chunk);
            String jsonChunk = objectMapper.writeValueAsString(chunkResponse);
            logger.debug("发送响应块到会话 {}: {}", session.getId(), jsonChunk);
            session.sendMessage(new TextMessage(jsonChunk));
        } catch (Exception e) {
            logger.error("发送响应块失败: {}", e.getMessage(), e);
        }
    }

    private void sendCompletionNotification(WebSocketSession session) {
        try {
            long currentTime = System.currentTimeMillis();
            Map<String, Object> notification = Map.of(
                "type", "completion",
                "status", "finished", 
                "message", "响应已完成",
                "timestamp", currentTime,
                "date", java.time.LocalDateTime.now().toString()
            );
            String notificationJson = objectMapper.writeValueAsString(notification);
            logger.info("发送完成通知到会话 {}: {}", session.getId(), notificationJson);
            session.sendMessage(new TextMessage(notificationJson));
            logger.info("已发送响应完成通知到会话: {}", session.getId());
        } catch (Exception e) {
            logger.error("发送完成通知失败: {}", e.getMessage(), e);
        }
    }

    private void handleError(WebSocketSession session, Throwable error) {
        logger.error("AI服务错误: {}", error.getMessage(), error);
        try {
            Map<String, String> errorResponse = Map.of("error", "AI服务暂时不可用，请稍后重试");
            String errorJson = objectMapper.writeValueAsString(errorResponse);
            logger.error("发送错误消息到会话 {}: {}", session.getId(), errorJson);
            session.sendMessage(new TextMessage(errorJson));
            logger.error("已发送错误消息到会话: {}", session.getId());
        } catch (Exception e) {
            logger.error("发送错误消息失败: {}", e.getMessage(), e);
        }
    }

    /**
     * 停止响应 
     */
    public void stopResponse(String userId, WebSocketSession session) {
        String sessionId = session.getId();
        logger.info("收到停止请求，用户ID: {}, 会话ID: {}", userId, sessionId);
        
        // 设置停止标志
        stopFlags.put(sessionId, true);
        
        // 发送停止确认
        try {
            long currentTime = System.currentTimeMillis();
            Map<String, Object> response = Map.of(
                "type", "stop", 
                "message", "响应已停止",
                "timestamp", currentTime,
                "date", java.time.Instant.ofEpochMilli(currentTime).toString()
            );
            String stopJson = objectMapper.writeValueAsString(response);
            logger.info("发送停止确认到会话 {}: {}", sessionId, stopJson);
            session.sendMessage(new TextMessage(stopJson));
            logger.info("已发送停止确认，会话ID: {}", sessionId);
        } catch (Exception e) {
            logger.error("发送停止确认失败: {}", e.getMessage(), e);
        }
        
        // 清理停止标志（延迟清理，避免影响当前响应）
        new Thread(() -> {
            try {
                Thread.sleep(2000); // 等待2秒
                stopFlags.remove(sessionId);
                logger.debug("已清理停止标志，会话ID: {}", sessionId);
            } catch (InterruptedException e) {
                Thread.currentThread().interrupt();
            }
        }).start();
    }
}
